### ISSUE TITLE
Show Impls instead of all functions

### ISSUE THREAD

**Issue by douweschulte** [cargo-public-api/cargo-public-api#36]
As part of the tree data structure I was thinking about showing the `impl`s of a `struct`/`enum`/`trait` instead of the full list of functions. For local traits the functions will already be in the list (in the trait definition) and for other traits the functions can be assumed to be known or at least less part of this crates api and more for that other crate. Also this should remove clutter if only a `trait` is updated this should only list this change one time and not for every entity implementing it.

Implementing this change would be a nice first step for a more tree like data structure as discussed before. I have already tried some things locally but nothing is working yet.

Mock up:
```rust
#[derive(Clone, Copy, Debug)]
pub struct Plain {
    pub x: usize,
}
```
Output:
```
pub struct comprehensive_api::structs::Plain
Implements: Clone, Copy, Debug
```

**Comment by Enselic** [comment]
I completely agree that it very well could make sense to show what traits are implemented rather than what functions (of traits) that are implemented. I'm not sure either exactly how to present it or diff it. But please continue experimenting and let me know if you figure out a good way :)

**Comment by repi** [comment]
this would indeed be great, and important also for things like empty marker traits that do not have any functions or types in them, but if a type derives them or not is still semver-relevant and affect the public API.

**Comment by Enselic** [comment]
I just merged https://github.com/Enselic/cargo-public-api/pull/152, so from now on, auto trait implementations are part of the output. These are a simple special case of `impl` rendering since there is never any associated items, so auto traits can always be rendered on one line as one item.

**Comment by Enselic** [comment]
https://github.com/Enselic/cargo-public-api/pull/195 makes the output contain impls themselves (and their associated items), rather than "cherry-picking" only the associated items of impls.

The proposed expected output `Implements: Clone, Copy, Debug` will not work in the general case unfortunately, since impls can be parameterized by both lifetimes and generic args and generic bounds. So for full public API fidelity, we need to include the `impl` items themselves in the output.

The way I see it, https://github.com/Enselic/cargo-public-api/pull/195 will close this issue. But I am more than happy to discuss and iterate on the details.

**Comment by douweschulte** [comment]
I agree this seems like a nice implementation. The proposed syntax indeed does not solve the general case.
